#!/usr/bin/env python

bld.SAMBA3_MODULE('vfs_skel_opaque',
                 subsystem='vfs',
                 source='irods_smb.cpp',
                 deps='samba-util',
                 init_function='',
                 internal_module=bld.SAMBA3_IS_STATIC_MODULE('vfs_skel_opaque'),
                 enabled=bld.SAMBA3_IS_ENABLED_MODULE('vfs_skel_opaque'))

